spring.application.name=CART-SERVICE
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/cart_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=manager
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


jwt.secret=w?fjIB5a#b%(C,,C;zp(1kZZ:%yp1W)@rn;]|0Dqd+=
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000


razorpay.key.id=rzp_test_TLGuvFstVO3wOe
razorpay.key.secret=0PIYky6UKuddo4d7CreH1E0b
